name: AlgoSec Action
on: [pull_request]
jobs:
  AlgoSec-Code-Analysis:
    runs-on: ubuntu-latest
    env:
      working_directory: ./tf-test
    defaults:
      run:
        working-directory: ${{ env.working_directory }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Format
        id: fmt
        run: |
          echo '::echo::on'
          echo 'STDOUT<<EOF' >> $GITHUB_ENV
          terraform fmt -check >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
          echo "::set-output name=content::$GITHUB_ENV"
        continue-on-error: true
      - name: display string
        run: |
          echo "The string is: ${{ steps.fmt.outputs.content }}"
      - run: echo stdout ${{ steps.fmt.outputs.stdout }}
      - run: echo stderr ${{ steps.fmt.outputs.stderr }}
      - run: echo exitcode ${{ steps.fmt.outputs.exitcode }}