name: AlgoSec Action
on: [ pull_request ]
jobs:
  AlgoSec-Code-Analysis:
    runs-on: ubuntu-latest
    env:
      working_directory: ./tf-test-sg
    defaults:
      run:
        working-directory: ${{ env.working_directory }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        #Is required for the plan's command
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      ################################ Terraform steps ################################
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}


      - name: Terraform Fmt
        id: fmt
        run: terraform fmt -check -diff
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init -no-color
        continue-on-error: true

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        continue-on-error: true

      - name: Terraform Plan
        id: plan
        run: terraform plan -input=false -no-color
        continue-on-error: true

      - name: Comment on PR
        # update Pull Request by the operation status
        uses: actions/github-script@v5
        env:
          format_out: ${{ steps.fmt.outputs.stdout }}
          format_err: ${{ steps.fmt.outputs.stderr }}
          init_out: ${{ steps.init.outputs.stdout }}
          init_err: ${{ steps.init.outputs.stderr }}
          validate_out: ${{ steps.validate.outputs.stdout }}
          validate_err: ${{ steps.validate.outputs.stderr }}
          plan: "${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const CODE_BLOCK = '```';
            const fmt_result = '${{ steps.fmt.outcome }}' === 'failure' ? ':x:' : ':heavy_check_mark:';
            const init_result = '${{ steps.init.outcome }}' === 'failure' ? ':x:' : ':heavy_check_mark:';
            const validate_result = '${{ steps.validate.outcome }}' === 'failure' ? ':x:' : ':heavy_check_mark:';
            const plan_result = '${{ steps.plan.outcome }}' === 'failure' ? ':x:' : ':heavy_check_mark:';
            const output = `
            ### :heavy_check_mark: Terraform Format and Style 🎨
            <details><summary>Logs</summary>
            Output

            ${ CODE_BLOCK }diff
            ${ process.env.format_out }
            ${ CODE_BLOCK }
            
            Errors

            ${ CODE_BLOCK }
            ${ process.env.format_err }
            ${ CODE_BLOCK }
            
            </details> <!-- End Format Logs -->

            ### ${ init_result } Terraform Initialization ⚙️
            <details><summary>Logs</summary>
            Output

            ${ CODE_BLOCK }
            ${ process.env.init_out }
            ${ CODE_BLOCK }

            Errors

            ${ CODE_BLOCK }
            ${ process.env.init_err }
            ${ CODE_BLOCK }

            </details> <!-- End Init Logs -->
            
            ### ${ validate_result } Terraform Validation 🤖
            <details><summary>Logs</summary>
            Output
            
            ${ CODE_BLOCK }
            ${ process.env.validate_out }
            ${ CODE_BLOCK }
            
            Errors
            
            ${ CODE_BLOCK }
            ${ process.env.validate_err }
            ${ CODE_BLOCK }
            
            </details> <!-- End Validate Logs -->
            
            ### ${ plan_result } Terraform Plan 📖
            <details><summary>Logs</summary>
            
            ${ CODE_BLOCK }terraform
            ${ process.env.plan }
            ${ CODE_BLOCK }
            
            </details>
            
            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })


      - name: Check Teraform results
        shell: bash
        run: |
          echo init ${{ steps.init.outputs.exitcode }}
          test ${{ steps.init.outputs.exitcode }} -eq 0
          echo validate ${{ steps.validate.outputs.exitcode }}
          test ${{ steps.validate.outputs.exitcode }} -eq 0
          echo plan ${{ steps.plan.outputs.exitcode }}
          test ${{ steps.plan.outputs.exitcode }} -eq 0

      ################################ Aws steps ################################
      - name: Generate uuid for tmp file name
        id: generate-uuid
        uses: filipstefansson/uuid-action@v1
        with:
          name: ${{ github.sha }}

      - name: Store plan's output into file
        # It's required to use this way to write the plan's output into file as a result that the output is multiline text
        run: |
          cat << EOF > tmp.out
          ${{ steps.plan.outputs.stdout }}
          EOF

      - name: Copy tmp file into S3
        run: |
          aws s3 cp tmp.out s3://vitalylanda-test/github-codeanalysis/tmp${{ steps.generate-uuid.outputs.uuid }}.out --metadata customer=${{ github.repository_owner }},action_id=${{ steps.generate-uuid.outputs.uuid }}

      - name: Wait till analysis complete
        id: analysis_status
        shell: bash
        run: |
          for(( i=1; i<=10; i++ )) 
          do 
            output=$(curl -s "https://31p8mo93gl.execute-api.us-east-1.amazonaws.com/dev/response?customer=${{ github.repository_owner }}&action_id=${{ steps.generate-uuid.outputs.uuid }}");
#            echo $output
            status=$(echo $output | jq -r '.message_found');
#            echo $status
            if [ $status = "true" ] 
              then 
                break
              else
                sleep 30
            fi 
          done
          echo $output

      - name: Comment analyze on PR
        uses: actions/github-script@v5
        env:
          analysis_out: ${{ steps.analysis_status.outputs.stdout }}
          analysis_err: ${{ steps.analysis_status.outputs.stderr }}
          plan: "${{ steps.analysis_status.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const CODE_BLOCK = '```';
            const analysis_result = '${{ steps.analysis_status.outcome }}' === 'failure' ? ':x:' : ':heavy_check_mark:';
            
            const output= '
            ###  ${ analysis_result }: Code Analysis 🎨
            <details><summary>Logs</summary>
            Output

            ${ CODE_BLOCK }
            ${ process.env.analysis_out }
            ${ CODE_BLOCK }

            Errors

            ${ CODE_BLOCK }
            ${ process.env.analysis_err }
            ${ CODE_BLOCK }

            </details> 
            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;
            '
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })