name: AlgoSec Action
on: [pull_request]
jobs:
  AlgoSec-Code-Analysis:
    runs-on: ubuntu-latest
    env:
      working_directory: ./tf-test
    defaults:
      run:
        working-directory: ${{ env.working_directory }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init
        continue-on-error: true

      - uses: actions/github-script@v5
        if: steps.init.outcome == 'failure'
        env:
          PLAN: "terraform\n out:${{ steps.init.outputs.stdout }}\n err:${{ steps.init.outputs.stderr }}"
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            script: |
              const output = `#### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
              
              <details><summary>Show Plan</summary>
              
              \`\`\`\n
              ${process.env.PLAN}
              \`\`\`
              
              </details>
              
              *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;
                
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: output
              })


      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color