name: 'Customer Repo CI/CD'
on:
  pull_request:
    branches:
      - 'main'
jobs:
  algosec-risk-analysis:
     name: 'Algosec Risk Analysis'
     runs-on: ubuntu-latest
     steps:
        - name: debug
          uses: hmarr/debug-action@v2
        - name: Algosec Risk Analysis Action
          uses: alonnalgoDevSecOps/risk-analysis-action@v0.0.6
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            GITHUB_SHA: ${{ github.sha }}
            GITHUB_WORKSPACE: ${{ github.workspace }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_REGION: us-west-2
            AWS_S3: ${{ secrets.AWS_S3 }}
            RA_API_URL: ${{ secrets.RA_API_URL }}
            TF_VERSION: '1.2.0'
  checkov-test-job:
    name: 'test job'
    runs-on: ubuntu-latest
    steps:
    - name: test checkov
      uses: skyfjell/tf-checkov-action@latest
      with:
        terraform_token: ${{ secrets.TF_API_TOKEN }}
  
      

          
          
          
         

