name: AlgoSec_Client_CI/CD
on:
  pull_request:
    branches:
      - 'main'
jobs:
#   debug:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: hmarr/debug-action@v2
#   AlgosecRiskAnalysisWorkflow:
#     uses: algosec/risk-analysis-workflow/.github/workflows/release.yml@main
#     secrets:
#       GH_TOKEN: ${{ secrets.GH_TOKEN }}
#       TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
#       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}

  algosec-risk-analysis-action:
     runs-on: ubuntu-latest
     steps:
      - name: debug
        uses: hmarr/debug-action@v2
      - name: checkout repo
        uses: actions/checkout@v3
      - name: typescript-container-action
        uses: alonnalgo/typescript-container-action@v0.0.14
        env:
          GITHUB_BASE_REF: ${{ inputs.GITHUB_BASE_REF }}
          GITHUB_SHA: ${{ inputs.GITHUB_SHA }}
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_BASE_REF: ${{ inputs.GITHUB_BASE_REF }}
          GITHUB_SHA: ${{ inputs.GITHUB_SHA }}
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}

