name: AlgoSec_Client_CI/CD
on:
  pull_request:
    branches:
      - 'main'
jobs:
#   AlgosecRiskAnalysisWorkflow:
#     uses: algosec/risk-analysis-workflow/.github/workflows/release.yml@main
#     secrets:
#       GH_TOKEN: ${{ secrets.GH_TOKEN }}
#       TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
#       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AlgosecRiskAnalysisAction:
    runs-on: ubuntu-latest
    steps:
      - name: AlgosecRiskAnalysisActionTEST
        uses: algosec/risk-analysis-action-github@v0.0.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

