name: 'Customer Repo CI/CD'
on:
  pull_request:
    branches:
      - 'main'
jobs:
  algosec-risk-analysis-job:
     name: 'Algosec Risk Analysis Job'
     runs-on: ubuntu-latest
     steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: 'Algosec Risk Analysis Action'
        uses: alonnalgo/action-test@v0.0.46
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_REGION: us-west-2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_BASE_REF: ${{ github.base_ref }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_WORKSPACE: ${{ github.workspace }}
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
          RA_API_URL: ${{ secrets.RA_API_URL }}
          AWS_S3: ${{ secrets.AWS_S3 }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}

