name: AlgoSec_Client_CI/CD
on:
  pull_request:
    branches:
      - 'main'
env:
  S3_DEST: devsecops-dev/github-codeanalysis
  API_URL: "https://31p8mo93gl.execute-api.us-east-1.amazonaws.com/dev/response"
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/debug-action@v2
  Risk_Analysis_Github_Action_TEST:
    uses: alonnalgo/risk-analysis-github-action/blob/main/.github/workflows/AlgoSecCodeAnalysis.yml@main
    secrets: inherit
