name: AlgoSec_Client_CI/CD
on:
  pull_request:
    branches:
      - 'main'
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/debug-action@v2
  AlgosecRiskAnalysisWorkflow:
    uses: algosec/risk-analysis-workflow/.github/workflows/release.yml@main
    secrets: inherit
