name: AlgoSec_Client_CI/CD
on:
  pull_request:
    branches:
      - 'main'
env:
  S3_DEST: devsecops-dev/github-codeanalysis
  API_URL: "https://31p8mo93gl.execute-api.us-east-1.amazonaws.com/dev/response"
jobs:
  Risk_Analysis_Github_Action_TEST:
    runs-on: ubuntu-latest
      # Make sure we have some code to diff.
      - name: TEST GITHUB ACTION ALGOSEC
        uses: alonnalgo/risk-analysis-github-action@v1.0.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
