name: AlgoSec_Client_CI/CD
on:
  pull_request:
    branches:
      - 'main'
jobs:
#   debug:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: hmarr/debug-action@v2
#   AlgosecRiskAnalysisWorkflow:
#     uses: algosec/risk-analysis-workflow/.github/workflows/release.yml@main
#     secrets:
#       GH_TOKEN: ${{ secrets.GH_TOKEN }}
#       TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
#       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}

  algosec-risk-analysis-action:
     runs-on: ubuntu-latest
     steps:
      - name: debug
        uses: hmarr/debug-action@v2
      - name: checkout repo
        uses: actions/checkout@v3
      - name: 'Docker Action'
        uses: alonnalgo/docker-action@v0.0.1
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_BASE_REF: ${{ github.base_ref }}
          GH_SHA: ${{ github.sha }}
          TF_TOKEN: ${{ secrets.TF_API_TOKEN }}
          TF_VERSION: '1.2.5'
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}

